import {
  User,
  Lead,
  Task,
  Client,
  DashboardMetrics,
  PerformanceMetrics
} from './types';
import { USER_PERMISSIONS } from './types';

// Dados mock dos usuários
export const mockUsers: User[] = [
  {
    id: '1',
    name: 'Kauan Santos',
    email: 'kauan@mettaassessoria.com',
    password: 'admin123', // Em produção seria um hash
    role: 'admin',
    avatar: '/avatars/kauan.jpg',
    createdAt: new Date('2024-01-01'),
    isActive: true,
    permissions: [...USER_PERMISSIONS.admin],
    lastLogin: new Date('2024-12-01'),
  },
  {
    id: '2',
    name: 'Maria Silva',
    email: 'maria@mettaassessoria.com',
    password: 'maria123',
    role: 'sdr',
    avatar: '/avatars/maria.jpg',
    createdAt: new Date('2024-01-15'),
    isActive: true,
    permissions: [...USER_PERMISSIONS.sdr],
    lastLogin: new Date('2024-12-01'),
  },
  {
    id: '3',
    name: 'João Oliveira',
    email: 'joao@mettaassessoria.com',
    password: 'joao123',
    role: 'closer',
    avatar: '/avatars/joao.jpg',
    createdAt: new Date('2024-02-01'),
    isActive: true,
    permissions: [...USER_PERMISSIONS.closer],
    lastLogin: new Date('2024-12-01'),
  },
  {
    id: '4',
    name: 'Ana Costa',
    email: 'ana@mettaassessoria.com',
    password: 'ana123',
    role: 'designer',
    avatar: '/avatars/ana.jpg',
    createdAt: new Date('2024-02-15'),
    isActive: true,
    permissions: [...USER_PERMISSIONS.designer],
    lastLogin: new Date('2024-12-01'),
  },
  {
    id: '5',
    name: 'Pedro Santos',
    email: 'pedro@mettaassessoria.com',
    password: 'pedro123',
    role: 'traffic_manager',
    avatar: '/avatars/pedro.jpg',
    createdAt: new Date('2024-03-01'),
    isActive: true,
    permissions: [...USER_PERMISSIONS.traffic_manager],
    lastLogin: new Date('2024-12-01'),
  },
];

// Dados mock dos leads
export const mockLeads: Lead[] = [
  {
    id: '1',
    name: 'João Silva',
    email: 'joao@empresa.com',
    phone: '(11) 99999-9999',
    company: 'Empresa ABC',
    status: 'qualificacao',
    origin: 'whatsapp',
    score: 'A',
    assignedTo: '2',
    createdAt: new Date('2024-12-01'),
    lastContact: new Date('2024-12-01'),
    notes: 'Lead interessado em marketing digital',
    value: 5000,
  },
  {
    id: '2',
    name: 'Maria Santos',
    email: 'maria@empresa.com',
    phone: '(11) 88888-8888',
    company: 'Empresa XYZ',
    status: 'contato',
    origin: 'instagram',
    score: 'B',
    assignedTo: '2',
    createdAt: new Date('2024-11-28'),
    lastContact: new Date('2024-12-01'),
    notes: 'Aguardando retorno da proposta',
    value: 8000,
  },
  {
    id: '3',
    name: 'Carlos Oliveira',
    email: 'carlos@empresa.com',
    phone: '(11) 77777-7777',
    company: 'Empresa 123',
    status: 'reuniao',
    origin: 'referral',
    score: 'A',
    assignedTo: '3',
    createdAt: new Date('2024-11-25'),
    lastContact: new Date('2024-12-01'),
    notes: 'Reunião agendada para próxima semana',
    value: 12000,
  },
  {
    id: '4',
    name: 'Fernanda Costa',
    email: 'fernanda@empresa.com',
    phone: '(11) 66666-6666',
    company: 'Empresa DEF',
    status: 'proposta',
    origin: 'google',
    score: 'B',
    assignedTo: '3',
    createdAt: new Date('2024-11-20'),
    lastContact: new Date('2024-11-30'),
    notes: 'Proposta enviada, aguardando aprovação',
    value: 15000,
  },
];

// Dados mock das tarefas
export const mockTasks: Task[] = [
  {
    id: '1',
    title: 'Criar identidade visual para Cliente ABC',
    description: 'Desenvolver logo, cores e padrões visuais para a marca',
    status: 'em_andamento',
    priority: 'alta',
    assignedTo: '4',
    clientId: '1',
    dueDate: new Date('2024-12-15'),
    estimatedHours: 16,
    actualHours: 8,
    tags: ['design', 'identidade-visual'],
    createdAt: new Date('2024-12-01'),
    updatedAt: new Date('2024-12-01'),
  },
  {
    id: '2',
    title: 'Briefing inicial com Cliente XYZ',
    description: 'Reunião para entender necessidades e objetivos',
    status: 'backlog',
    priority: 'media',
    assignedTo: '2',
    clientId: '2',
    dueDate: new Date('2024-12-10'),
    estimatedHours: 2,
    tags: ['briefing', 'reuniao'],
    createdAt: new Date('2024-12-01'),
    updatedAt: new Date('2024-12-01'),
  },
  {
    id: '3',
    title: 'Configurar campanha Google Ads',
    description: 'Criar e configurar campanhas de anúncios',
    status: 'revisao',
    priority: 'alta',
    assignedTo: '5',
    clientId: '1',
    dueDate: new Date('2024-12-12'),
    estimatedHours: 8,
    actualHours: 6,
    tags: ['google-ads', 'campanha'],
    createdAt: new Date('2024-11-28'),
    updatedAt: new Date('2024-12-01'),
  },
  {
    id: '4',
    title: 'Revisar proposta comercial',
    description: 'Ajustar valores e condições da proposta',
    status: 'concluida',
    priority: 'urgente',
    assignedTo: '3',
    clientId: '3',
    dueDate: new Date('2024-12-05'),
    estimatedHours: 4,
    actualHours: 3,
    tags: ['proposta', 'comercial'],
    createdAt: new Date('2024-11-30'),
    updatedAt: new Date('2024-12-01'),
    completedAt: new Date('2024-12-01'),
  },
  {
    id: '5',
    title: 'Criar post para Instagram',
    description: 'Desenvolver conteúdo para rede social',
    status: 'backlog',
    priority: 'baixa',
    assignedTo: '4',
    clientId: '2',
    dueDate: new Date('2024-12-20'),
    estimatedHours: 3,
    tags: ['instagram', 'social-media'],
    createdAt: new Date('2024-12-01'),
    updatedAt: new Date('2024-12-01'),
  },
  {
    id: '6',
    title: 'Análise de concorrência',
    description: 'Pesquisar e analisar concorrentes diretos',
    status: 'em_andamento',
    priority: 'media',
    assignedTo: '2',
    clientId: '4',
    dueDate: new Date('2024-12-18'),
    estimatedHours: 6,
    actualHours: 2,
    tags: ['analise', 'concorrencia'],
    createdAt: new Date('2024-11-29'),
    updatedAt: new Date('2024-12-01'),
  },
];

// Dados mock dos clientes
export const mockClients: Client[] = [
  {
    id: '1',
    name: 'Empresa ABC',
    email: 'contato@empresaabc.com',
    phone: '(11) 55555-5555',
    company: 'Empresa ABC Ltda',
    plan: 'Plano Premium',
    contractStatus: 'ativo',
    activeMonths: 6,
    monthlyValue: 5000,
    createdAt: new Date('2024-06-01'),
    lastContact: new Date('2024-12-01'),
    notes: 'Cliente satisfeito, possibilidade de upsell',
  },
  {
    id: '2',
    name: 'Empresa XYZ',
    email: 'contato@xyz.com',
    phone: '(11) 44444-4444',
    company: 'XYZ Comércio',
    plan: 'Plano Básico',
    contractStatus: 'ativo',
    activeMonths: 3,
    monthlyValue: 3000,
    createdAt: new Date('2024-09-01'),
    lastContact: new Date('2024-11-30'),
    notes: 'Cliente novo, ainda em adaptação',
  },
  {
    id: '3',
    name: 'Empresa 123',
    email: 'contato@123.com',
    phone: '(11) 33333-3333',
    company: '123 Serviços',
    plan: 'Plano Intermediário',
    contractStatus: 'pendente',
    activeMonths: 0,
    monthlyValue: 4000,
    createdAt: new Date('2024-11-25'),
    lastContact: new Date('2024-12-01'),
    notes: 'Aguardando assinatura do contrato',
  },
];

// Métricas do dashboard
export const getDashboardMetrics = (): DashboardMetrics => {
  return {
    activeLeads: mockLeads.filter(lead => lead.status !== 'fechado' && lead.status !== 'perdido').length,
    monthlySales: '15.5k',
    activeClients: mockClients.filter(client => client.contractStatus === 'ativo').length,
    pendingTasks: mockTasks.filter(task => task.status !== 'concluida').length,
  };
};

// Métricas de performance por usuário
export const getPerformanceMetrics = (): PerformanceMetrics[] => {
  return mockUsers.map(user => ({
    userId: user.id,
    leadsQualified: Math.floor(Math.random() * 20) + 5,
    meetingsScheduled: Math.floor(Math.random() * 15) + 3,
    dealsClosed: Math.floor(Math.random() * 8) + 1,
    revenue: Math.floor(Math.random() * 50000) + 10000,
    tasksCompleted: Math.floor(Math.random() * 25) + 10,
    hoursWorked: Math.floor(Math.random() * 160) + 80,
  }));
};
